# Grantmaker settings
foundation_name: CS 639 Final Project
foundation_tagline: >
  Learning-Based Computer Vision
  on Facial Expression Recognition
grant_application_login: 

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
profile_twitter: 
profile_facebook: 
profile_instagram: 
profile_github: https://github.com/LynetteGao

# Site settings
title: # Defaults to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  The is demo page
# Google settings
live: false # enter 'true' when you're ready for the site to be indexed by Google and other web crawlers

# Jekyll settings
baseurl: /639-project # Leave this blank unless your site is located on a subpath, e.g. /blog
url:  # Typically http://www.yourdomain.org
collections:
  featured-cards:
    output: true
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
  - /images/photoshop-helpers
